import fetch from 'node-fetch'
let handler = async (m, { conn }) => {
  let caption =  `
╭─[K29-MD]───╮
 | 
│╭────────────────────
┴│👋 Hey there, ${conn.getName(m.sender)}!
⬡│🤖 I\'m K29-MD \n⬡│ I\'m up and running! 🚀
│╰────────────────────
┠───[ *BOT INFO* ]────╮
│╭────────────────────
┴│    K29PROMAX 
⬡│💻 A WhatsApp bot created by:
⬡│👨‍💻 K29PROMAX 
⬡│📞 For any inquiries, contact:
⬡│📱 wa.me/263717672068
💛🚦 wa.me/263717672068
⬡│🙅‍♂️ Don't call the owner or you'll be
⬡│ ignored or blocked motherfucker😂🖕
││  Follow the K29promax channel on WhatsApp: https://whatsapp.com/channel/0029VadkTYX4tRrovXR05g0k
*Generated by *K29PROMAX*
`.trim()
}
handler.help = ['alive']
handler.tags = ['bot check']
handler.command = /^(alive|Hi)$/i


export default handler
